// Package auth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package auth

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "BasicAuth.Scopes"
)

// Defines values for GrantType.
const (
	UrnIetfParamsOauthGrantTypeDeviceCode GrantType = "urn:ietf:params:oauth:grant-type:device_code"
)

// Defines values for RefreshTokenRequestGrantType.
const (
	RefreshToken RefreshTokenRequestGrantType = "refresh_token"
)

// AccessTokenResponse OAuth 2 access token success response (RFC 6749 §5.1).
type AccessTokenResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Optional refresh token for later renewal (Cognito).
	RefreshToken *string `json:"refresh_token,omitempty"`
	TokenType    string  `json:"token_type"`
}

// DeviceAuthorizationRequest defines model for DeviceAuthorizationRequest.
type DeviceAuthorizationRequest struct {
	// ClientId Public OAuth 2 client identifier.
	ClientId string `json:"client_id"`
}

// DeviceAuthorizationResponse RFC 8628 §3.2 device authorization response.
type DeviceAuthorizationResponse struct {
	DeviceCode string `json:"device_code"`

	// ExpiresIn Lifetime of the `device_code` in seconds.
	ExpiresIn int `json:"expires_in"`

	// Interval Minimum polling interval in seconds; client may increase on `slow_down`.
	Interval        int    `json:"interval"`
	UserCode        string `json:"user_code"`
	VerificationUri string `json:"verification_uri"`

	// VerificationUriComplete Pre-filled verification URI (preferred for UX).
	VerificationUriComplete *string `json:"verification_uri_complete,omitempty"`
}

// DeviceTokenPollRequest defines model for DeviceTokenPollRequest.
type DeviceTokenPollRequest struct {
	ClientId   string `json:"client_id"`
	DeviceCode string `json:"device_code"`

	// GrantType A grant type to request.
	GrantType GrantType `json:"grant_type"`
}

// GrantType A grant type to request.
type GrantType string

// OAuth2ErrorResponse OAuth 2 error response (RFC 6749 §5.2).
type OAuth2ErrorResponse struct {
	// Error Machine-readable error code. Observed values include
	// `authorization_pending`, `slow_down`, `expired_token`, `invalid_grant`.
	Error *string `json:"error,omitempty"`

	// ErrorDescription Human-readable detail; may be empty.
	ErrorDescription *string `json:"error_description,omitempty"`
}

// RefreshTokenRequest Cognito `/oauth2/token` body for the refresh_token grant (RFC 6749).
type RefreshTokenRequest struct {
	// ClientId Same public client_id as the device flow.
	ClientId     string                       `json:"client_id"`
	GrantType    RefreshTokenRequestGrantType `json:"grant_type"`
	RefreshToken string                       `json:"refresh_token"`
}

// RefreshTokenRequestGrantType defines model for RefreshTokenRequest.GrantType.
type RefreshTokenRequestGrantType string

// ClientIdQuery defines model for ClientIdQuery.
type ClientIdQuery = string

// DeviceCodeQuery defines model for DeviceCodeQuery.
type DeviceCodeQuery = string

// GrantTypeQuery A grant type to request.
type GrantTypeQuery = GrantType

// PostTokenFormdataBody defines parameters for PostToken.
type PostTokenFormdataBody struct {
	union json.RawMessage
}

// PostTokenParams defines parameters for PostToken.
type PostTokenParams struct {
	// ClientId OAuth 2 `client_id`. Sent in both query and body by the client.
	ClientId *ClientIdQuery `form:"client_id,omitempty" json:"client_id,omitempty"`

	// DeviceCode Device code from step A. Required for step B (poll).
	DeviceCode *DeviceCodeQuery `form:"device_code,omitempty" json:"device_code,omitempty"`

	// GrantType Required for step B; must be the device code grant type.
	GrantType *GrantTypeQuery `form:"grant_type,omitempty" json:"grant_type,omitempty"`
}

// PostOAuth2TokenRefreshFormdataRequestBody defines body for PostOAuth2TokenRefresh for application/x-www-form-urlencoded ContentType.
type PostOAuth2TokenRefreshFormdataRequestBody = RefreshTokenRequest

// PostTokenFormdataRequestBody defines body for PostToken for application/x-www-form-urlencoded ContentType.
type PostTokenFormdataRequestBody PostTokenFormdataBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostOAuth2TokenRefreshWithBody request with any body
	PostOAuth2TokenRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostOAuth2TokenRefreshWithFormdataBody(ctx context.Context, body PostOAuth2TokenRefreshFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTokenWithBody request with any body
	PostTokenWithBody(ctx context.Context, params *PostTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTokenWithFormdataBody(ctx context.Context, params *PostTokenParams, body PostTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostOAuth2TokenRefreshWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOAuth2TokenRefreshRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostOAuth2TokenRefreshWithFormdataBody(ctx context.Context, body PostOAuth2TokenRefreshFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostOAuth2TokenRefreshRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTokenWithBody(ctx context.Context, params *PostTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTokenRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTokenWithFormdataBody(ctx context.Context, params *PostTokenParams, body PostTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTokenRequestWithFormdataBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostOAuth2TokenRefreshRequestWithFormdataBody calls the generic PostOAuth2TokenRefresh builder with application/x-www-form-urlencoded body
func NewPostOAuth2TokenRefreshRequestWithFormdataBody(server string, body PostOAuth2TokenRefreshFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostOAuth2TokenRefreshRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostOAuth2TokenRefreshRequestWithBody generates requests for PostOAuth2TokenRefresh with any type of body
func NewPostOAuth2TokenRefreshRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/oauth2/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTokenRequestWithFormdataBody calls the generic PostToken builder with application/x-www-form-urlencoded body
func NewPostTokenRequestWithFormdataBody(server string, params *PostTokenParams, body PostTokenFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostTokenRequestWithBody(server, params, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostTokenRequestWithBody generates requests for PostToken with any type of body
func NewPostTokenRequestWithBody(server string, params *PostTokenParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/token")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ClientId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "client_id", runtime.ParamLocationQuery, *params.ClientId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.DeviceCode != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "device_code", runtime.ParamLocationQuery, *params.DeviceCode); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.GrantType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "grant_type", runtime.ParamLocationQuery, *params.GrantType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostOAuth2TokenRefreshWithBodyWithResponse request with any body
	PostOAuth2TokenRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOAuth2TokenRefreshResponse, error)

	PostOAuth2TokenRefreshWithFormdataBodyWithResponse(ctx context.Context, body PostOAuth2TokenRefreshFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostOAuth2TokenRefreshResponse, error)

	// PostTokenWithBodyWithResponse request with any body
	PostTokenWithBodyWithResponse(ctx context.Context, params *PostTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTokenResponse, error)

	PostTokenWithFormdataBodyWithResponse(ctx context.Context, params *PostTokenParams, body PostTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostTokenResponse, error)
}

type PostOAuth2TokenRefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccessTokenResponse
	JSONDefault  *OAuth2ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostOAuth2TokenRefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostOAuth2TokenRefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		union json.RawMessage
	}
	JSON4XX *OAuth2ErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostOAuth2TokenRefreshWithBodyWithResponse request with arbitrary body returning *PostOAuth2TokenRefreshResponse
func (c *ClientWithResponses) PostOAuth2TokenRefreshWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostOAuth2TokenRefreshResponse, error) {
	rsp, err := c.PostOAuth2TokenRefreshWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOAuth2TokenRefreshResponse(rsp)
}

func (c *ClientWithResponses) PostOAuth2TokenRefreshWithFormdataBodyWithResponse(ctx context.Context, body PostOAuth2TokenRefreshFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostOAuth2TokenRefreshResponse, error) {
	rsp, err := c.PostOAuth2TokenRefreshWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostOAuth2TokenRefreshResponse(rsp)
}

// PostTokenWithBodyWithResponse request with arbitrary body returning *PostTokenResponse
func (c *ClientWithResponses) PostTokenWithBodyWithResponse(ctx context.Context, params *PostTokenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTokenResponse, error) {
	rsp, err := c.PostTokenWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTokenResponse(rsp)
}

func (c *ClientWithResponses) PostTokenWithFormdataBodyWithResponse(ctx context.Context, params *PostTokenParams, body PostTokenFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostTokenResponse, error) {
	rsp, err := c.PostTokenWithFormdataBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTokenResponse(rsp)
}

// ParsePostOAuth2TokenRefreshResponse parses an HTTP response from a PostOAuth2TokenRefreshWithResponse call
func ParsePostOAuth2TokenRefreshResponse(rsp *http.Response) (*PostOAuth2TokenRefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostOAuth2TokenRefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccessTokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest OAuth2ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParsePostTokenResponse parses an HTTP response from a PostTokenWithResponse call
func ParsePostTokenResponse(rsp *http.Response) (*PostTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode/100 == 4:
		var dest OAuth2ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON4XX = &dest

	}

	return response, nil
}
