// Code generated by MockGen. DO NOT EDIT.
// Source: client.ifc.go
//
// Generated by this command:
//
//	mockgen -source=client.ifc.go -destination=client.mock.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientWithResponsesIfc is a mock of ClientWithResponsesIfc interface.
type MockClientWithResponsesIfc struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesIfcMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesIfcMockRecorder is the mock recorder for MockClientWithResponsesIfc.
type MockClientWithResponsesIfcMockRecorder struct {
	mock *MockClientWithResponsesIfc
}

// NewMockClientWithResponsesIfc creates a new mock instance.
func NewMockClientWithResponsesIfc(ctrl *gomock.Controller) *MockClientWithResponsesIfc {
	mock := &MockClientWithResponsesIfc{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesIfcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesIfc) EXPECT() *MockClientWithResponsesIfcMockRecorder {
	return m.recorder
}

// AddOrganizationMemberWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) AddOrganizationMemberWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddOrganizationMemberWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*AddOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganizationMemberWithBodyWithResponse indicates an expected call of AddOrganizationMemberWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) AddOrganizationMemberWithBodyWithResponse(ctx, organizationId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganizationMemberWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).AddOrganizationMemberWithBodyWithResponse), varargs...)
}

// AddOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) AddOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, body AddOrganizationMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*AddOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*AddOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganizationMemberWithResponse indicates an expected call of AddOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) AddOrganizationMemberWithResponse(ctx, organizationId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).AddOrganizationMemberWithResponse), varargs...)
}

// CreateInterfaceReleaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceReleaseWithBodyWithResponse(ctx context.Context, interfaceId InterfaceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceReleaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceReleaseWithBodyWithResponse indicates an expected call of CreateInterfaceReleaseWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceReleaseWithBodyWithResponse(ctx, interfaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceReleaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceReleaseWithBodyWithResponse), varargs...)
}

// CreateInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, body CreateInterfaceReleaseJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceReleaseWithResponse indicates an expected call of CreateInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceReleaseWithResponse(ctx, interfaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceReleaseWithResponse), varargs...)
}

// CreateInterfaceRevisionWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceRevisionWithBodyWithResponse(ctx context.Context, interfaceId InterfaceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceRevisionWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceRevisionWithBodyWithResponse indicates an expected call of CreateInterfaceRevisionWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceRevisionWithBodyWithResponse(ctx, interfaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceRevisionWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceRevisionWithBodyWithResponse), varargs...)
}

// CreateInterfaceRevisionWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceRevisionWithResponse(ctx context.Context, interfaceId InterfaceId, body CreateInterfaceRevisionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceRevisionWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceRevisionWithResponse indicates an expected call of CreateInterfaceRevisionWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceRevisionWithResponse(ctx, interfaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceRevisionWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceRevisionWithResponse), varargs...)
}

// CreateInterfaceWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceWithBodyWithResponse indicates an expected call of CreateInterfaceWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceWithBodyWithResponse), varargs...)
}

// CreateInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceWithResponse(ctx context.Context, body CreateInterfaceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceWithResponse indicates an expected call of CreateInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceWithResponse), varargs...)
}

// CreateOrganizationWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrganizationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationWithBodyWithResponse indicates an expected call of CreateOrganizationWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateOrganizationWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateOrganizationWithBodyWithResponse), varargs...)
}

// CreateOrganizationWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateOrganizationWithResponse(ctx context.Context, body CreateOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrganizationWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationWithResponse indicates an expected call of CreateOrganizationWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateOrganizationWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateOrganizationWithResponse), varargs...)
}

// DeleteInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, semVer SemanticVersion, reqEditors ...RequestEditorFn) (*DeleteInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, semVer}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInterfaceReleaseWithResponse indicates an expected call of DeleteInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteInterfaceReleaseWithResponse(ctx, interfaceId, semVer any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, semVer}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteInterfaceReleaseWithResponse), varargs...)
}

// DeleteInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteInterfaceWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*DeleteInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInterfaceWithResponse indicates an expected call of DeleteInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteInterfaceWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteInterfaceWithResponse), varargs...)
}

// DeleteOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, reqEditors ...RequestEditorFn) (*DeleteOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrganizationMemberWithResponse indicates an expected call of DeleteOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteOrganizationMemberWithResponse(ctx, organizationId, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteOrganizationMemberWithResponse), varargs...)
}

// GetHealthWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetHealthWithResponse", varargs...)
	ret0, _ := ret[0].(*GetHealthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHealthWithResponse indicates an expected call of GetHealthWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetHealthWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHealthWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetHealthWithResponse), varargs...)
}

// GetInterfaceByPathWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceByPathWithResponse(ctx context.Context, ownerScope GetInterfaceByPathParamsOwnerScope, ownerName, interfaceName string, params *GetInterfaceByPathParams, reqEditors ...RequestEditorFn) (*GetInterfaceByPathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ownerScope, ownerName, interfaceName, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceByPathWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceByPathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceByPathWithResponse indicates an expected call of GetInterfaceByPathWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceByPathWithResponse(ctx, ownerScope, ownerName, interfaceName, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ownerScope, ownerName, interfaceName, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceByPathWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceByPathWithResponse), varargs...)
}

// GetInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, semVer SemanticVersion, reqEditors ...RequestEditorFn) (*GetInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, semVer}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceReleaseWithResponse indicates an expected call of GetInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceReleaseWithResponse(ctx, interfaceId, semVer any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, semVer}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceReleaseWithResponse), varargs...)
}

// GetInterfaceRevisionWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceRevisionWithResponse(ctx context.Context, interfaceId InterfaceId, revisionId InterfaceRevisionId, reqEditors ...RequestEditorFn) (*GetInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, revisionId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceRevisionWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceRevisionWithResponse indicates an expected call of GetInterfaceRevisionWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceRevisionWithResponse(ctx, interfaceId, revisionId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, revisionId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceRevisionWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceRevisionWithResponse), varargs...)
}

// GetInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceWithResponse(ctx context.Context, interfaceId InterfaceId, params *GetInterfaceParams, reqEditors ...RequestEditorFn) (*GetInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceWithResponse indicates an expected call of GetInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceWithResponse(ctx, interfaceId, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceWithResponse), varargs...)
}

// GetOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, reqEditors ...RequestEditorFn) (*GetOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*GetOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMemberWithResponse indicates an expected call of GetOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetOrganizationMemberWithResponse(ctx, organizationId, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetOrganizationMemberWithResponse), varargs...)
}

// GetOrganizationSettingsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetOrganizationSettingsWithResponse(ctx context.Context, organizationId OrganizationId, reqEditors ...RequestEditorFn) (*GetOrganizationSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrganizationSettingsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetOrganizationSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationSettingsWithResponse indicates an expected call of GetOrganizationSettingsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetOrganizationSettingsWithResponse(ctx, organizationId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationSettingsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetOrganizationSettingsWithResponse), varargs...)
}

// GetUserSettingsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetUserSettingsWithResponse(ctx context.Context, userId UserId, reqEditors ...RequestEditorFn) (*GetUserSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserSettingsWithResponse", varargs...)
	ret0, _ := ret[0].(*GetUserSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSettingsWithResponse indicates an expected call of GetUserSettingsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetUserSettingsWithResponse(ctx, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSettingsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetUserSettingsWithResponse), varargs...)
}

// ListInterfaceReleasesWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfaceReleasesWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*ListInterfaceReleasesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfaceReleasesWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfaceReleasesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaceReleasesWithResponse indicates an expected call of ListInterfaceReleasesWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfaceReleasesWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaceReleasesWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfaceReleasesWithResponse), varargs...)
}

// ListInterfaceRevisionsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfaceRevisionsWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*ListInterfaceRevisionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfaceRevisionsWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfaceRevisionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaceRevisionsWithResponse indicates an expected call of ListInterfaceRevisionsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfaceRevisionsWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaceRevisionsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfaceRevisionsWithResponse), varargs...)
}

// ListInterfacesWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfacesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListInterfacesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfacesWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfacesWithResponse indicates an expected call of ListInterfacesWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfacesWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfacesWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfacesWithResponse), varargs...)
}

// ListOrganizationMembersWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListOrganizationMembersWithResponse(ctx context.Context, organizationId OrganizationId, reqEditors ...RequestEditorFn) (*ListOrganizationMembersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOrganizationMembersWithResponse", varargs...)
	ret0, _ := ret[0].(*ListOrganizationMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMembersWithResponse indicates an expected call of ListOrganizationMembersWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListOrganizationMembersWithResponse(ctx, organizationId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMembersWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListOrganizationMembersWithResponse), varargs...)
}

// ListOrganizationsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListOrganizationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOrganizationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOrganizationsWithResponse", varargs...)
	ret0, _ := ret[0].(*ListOrganizationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationsWithResponse indicates an expected call of ListOrganizationsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListOrganizationsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListOrganizationsWithResponse), varargs...)
}

// UpdateOrganizationMemberWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationMemberWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationMemberWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMemberWithBodyWithResponse indicates an expected call of UpdateOrganizationMemberWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationMemberWithBodyWithResponse(ctx, organizationId, userId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMemberWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationMemberWithBodyWithResponse), varargs...)
}

// UpdateOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, body UpdateOrganizationMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMemberWithResponse indicates an expected call of UpdateOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationMemberWithResponse(ctx, organizationId, userId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationMemberWithResponse), varargs...)
}

// UpdateOrganizationSettingsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationSettingsWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOrganizationSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationSettingsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationSettingsWithBodyWithResponse indicates an expected call of UpdateOrganizationSettingsWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationSettingsWithBodyWithResponse(ctx, organizationId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationSettingsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationSettingsWithBodyWithResponse), varargs...)
}

// UpdateOrganizationSettingsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationSettingsWithResponse(ctx context.Context, organizationId OrganizationId, body UpdateOrganizationSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOrganizationSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationSettingsWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationSettingsWithResponse indicates an expected call of UpdateOrganizationSettingsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationSettingsWithResponse(ctx, organizationId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationSettingsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationSettingsWithResponse), varargs...)
}

// UpdateUserSettingsWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateUserSettingsWithBodyWithResponse(ctx context.Context, userId UserId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserSettingsWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateUserSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserSettingsWithBodyWithResponse indicates an expected call of UpdateUserSettingsWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateUserSettingsWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSettingsWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateUserSettingsWithBodyWithResponse), varargs...)
}

// UpdateUserSettingsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateUserSettingsWithResponse(ctx context.Context, userId UserId, body UpdateUserSettingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserSettingsWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateUserSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserSettingsWithResponse indicates an expected call of UpdateUserSettingsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateUserSettingsWithResponse(ctx, userId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSettingsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateUserSettingsWithResponse), varargs...)
}
