// Code generated by MockGen. DO NOT EDIT.
// Source: client.ifc.go
//
// Generated by this command:
//
//	mockgen -source=client.ifc.go -destination=client.mock.go -package=client
//

// Package client is a generated GoMock package.
package client

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClientWithResponsesIfc is a mock of ClientWithResponsesIfc interface.
type MockClientWithResponsesIfc struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesIfcMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesIfcMockRecorder is the mock recorder for MockClientWithResponsesIfc.
type MockClientWithResponsesIfcMockRecorder struct {
	mock *MockClientWithResponsesIfc
}

// NewMockClientWithResponsesIfc creates a new mock instance.
func NewMockClientWithResponsesIfc(ctrl *gomock.Controller) *MockClientWithResponsesIfc {
	mock := &MockClientWithResponsesIfc{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesIfcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesIfc) EXPECT() *MockClientWithResponsesIfcMockRecorder {
	return m.recorder
}

// AddOrganizationMemberWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) AddOrganizationMemberWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AddOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddOrganizationMemberWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*AddOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganizationMemberWithBodyWithResponse indicates an expected call of AddOrganizationMemberWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) AddOrganizationMemberWithBodyWithResponse(ctx, organizationId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganizationMemberWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).AddOrganizationMemberWithBodyWithResponse), varargs...)
}

// AddOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) AddOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, body AddOrganizationMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*AddOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*AddOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrganizationMemberWithResponse indicates an expected call of AddOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) AddOrganizationMemberWithResponse(ctx, organizationId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).AddOrganizationMemberWithResponse), varargs...)
}

// CreateInterfaceReleaseWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceReleaseWithBodyWithResponse(ctx context.Context, interfaceId InterfaceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceReleaseWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceReleaseWithBodyWithResponse indicates an expected call of CreateInterfaceReleaseWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceReleaseWithBodyWithResponse(ctx, interfaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceReleaseWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceReleaseWithBodyWithResponse), varargs...)
}

// CreateInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, body CreateInterfaceReleaseJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceReleaseWithResponse indicates an expected call of CreateInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceReleaseWithResponse(ctx, interfaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceReleaseWithResponse), varargs...)
}

// CreateInterfaceRevisionWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceRevisionWithBodyWithResponse(ctx context.Context, interfaceId InterfaceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceRevisionWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceRevisionWithBodyWithResponse indicates an expected call of CreateInterfaceRevisionWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceRevisionWithBodyWithResponse(ctx, interfaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceRevisionWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceRevisionWithBodyWithResponse), varargs...)
}

// CreateInterfaceRevisionWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceRevisionWithResponse(ctx context.Context, interfaceId InterfaceId, body CreateInterfaceRevisionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceRevisionWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceRevisionWithResponse indicates an expected call of CreateInterfaceRevisionWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceRevisionWithResponse(ctx, interfaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceRevisionWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceRevisionWithResponse), varargs...)
}

// CreateInterfaceWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceWithBodyWithResponse indicates an expected call of CreateInterfaceWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceWithBodyWithResponse), varargs...)
}

// CreateInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateInterfaceWithResponse(ctx context.Context, body CreateInterfaceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInterfaceWithResponse indicates an expected call of CreateInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateInterfaceWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateInterfaceWithResponse), varargs...)
}

// CreateOrganizationWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrganizationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationWithBodyWithResponse indicates an expected call of CreateOrganizationWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateOrganizationWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateOrganizationWithBodyWithResponse), varargs...)
}

// CreateOrganizationWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) CreateOrganizationWithResponse(ctx context.Context, body CreateOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateOrganizationWithResponse", varargs...)
	ret0, _ := ret[0].(*CreateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrganizationWithResponse indicates an expected call of CreateOrganizationWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) CreateOrganizationWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganizationWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CreateOrganizationWithResponse), varargs...)
}

// CurrentUserID mocks base method.
func (m *MockClientWithResponsesIfc) CurrentUserID(ctx context.Context) (UserId, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUserID", ctx)
	ret0, _ := ret[0].(UserId)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUserID indicates an expected call of CurrentUserID.
func (mr *MockClientWithResponsesIfcMockRecorder) CurrentUserID(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserID", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).CurrentUserID), ctx)
}

// DeleteInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, semVer SemanticVersion, reqEditors ...RequestEditorFn) (*DeleteInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, semVer}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInterfaceReleaseWithResponse indicates an expected call of DeleteInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteInterfaceReleaseWithResponse(ctx, interfaceId, semVer any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, semVer}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteInterfaceReleaseWithResponse), varargs...)
}

// DeleteInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteInterfaceWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*DeleteInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInterfaceWithResponse indicates an expected call of DeleteInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteInterfaceWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteInterfaceWithResponse), varargs...)
}

// DeleteOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) DeleteOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, reqEditors ...RequestEditorFn) (*DeleteOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*DeleteOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteOrganizationMemberWithResponse indicates an expected call of DeleteOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) DeleteOrganizationMemberWithResponse(ctx, organizationId, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).DeleteOrganizationMemberWithResponse), varargs...)
}

// GetCurrentUserWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetCurrentUserWithResponse", varargs...)
	ret0, _ := ret[0].(*GetCurrentUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentUserWithResponse indicates an expected call of GetCurrentUserWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetCurrentUserWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentUserWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetCurrentUserWithResponse), varargs...)
}

// GetInterfaceByPathWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceByPathWithResponse(ctx context.Context, ownerScope GetInterfaceByPathParamsOwnerScope, ownerName, interfaceName string, params *GetInterfaceByPathParams, reqEditors ...RequestEditorFn) (*GetInterfaceByPathResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ownerScope, ownerName, interfaceName, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceByPathWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceByPathResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceByPathWithResponse indicates an expected call of GetInterfaceByPathWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceByPathWithResponse(ctx, ownerScope, ownerName, interfaceName, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ownerScope, ownerName, interfaceName, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceByPathWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceByPathWithResponse), varargs...)
}

// GetInterfaceReleaseWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceReleaseWithResponse(ctx context.Context, interfaceId InterfaceId, semVer SemanticVersion, reqEditors ...RequestEditorFn) (*GetInterfaceReleaseResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, semVer}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceReleaseWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceReleaseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceReleaseWithResponse indicates an expected call of GetInterfaceReleaseWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceReleaseWithResponse(ctx, interfaceId, semVer any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, semVer}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceReleaseWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceReleaseWithResponse), varargs...)
}

// GetInterfaceRevisionWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceRevisionWithResponse(ctx context.Context, interfaceId InterfaceId, revisionId InterfaceRevisionId, reqEditors ...RequestEditorFn) (*GetInterfaceRevisionResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, revisionId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceRevisionWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceRevisionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceRevisionWithResponse indicates an expected call of GetInterfaceRevisionWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceRevisionWithResponse(ctx, interfaceId, revisionId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, revisionId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceRevisionWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceRevisionWithResponse), varargs...)
}

// GetInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetInterfaceWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*GetInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*GetInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInterfaceWithResponse indicates an expected call of GetInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetInterfaceWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetInterfaceWithResponse), varargs...)
}

// GetOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, reqEditors ...RequestEditorFn) (*GetOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*GetOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationMemberWithResponse indicates an expected call of GetOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetOrganizationMemberWithResponse(ctx, organizationId, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetOrganizationMemberWithResponse), varargs...)
}

// GetOrganizationWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetOrganizationWithResponse(ctx context.Context, organizationId OrganizationId, reqEditors ...RequestEditorFn) (*GetOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetOrganizationWithResponse", varargs...)
	ret0, _ := ret[0].(*GetOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationWithResponse indicates an expected call of GetOrganizationWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetOrganizationWithResponse(ctx, organizationId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetOrganizationWithResponse), varargs...)
}

// GetUserWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) GetUserWithResponse(ctx context.Context, userId UserId, reqEditors ...RequestEditorFn) (*GetUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUserWithResponse", varargs...)
	ret0, _ := ret[0].(*GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithResponse indicates an expected call of GetUserWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) GetUserWithResponse(ctx, userId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).GetUserWithResponse), varargs...)
}

// ListInterfaceReleasesWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfaceReleasesWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*ListInterfaceReleasesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfaceReleasesWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfaceReleasesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaceReleasesWithResponse indicates an expected call of ListInterfaceReleasesWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfaceReleasesWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaceReleasesWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfaceReleasesWithResponse), varargs...)
}

// ListInterfaceRevisionsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfaceRevisionsWithResponse(ctx context.Context, interfaceId InterfaceId, reqEditors ...RequestEditorFn) (*ListInterfaceRevisionsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfaceRevisionsWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfaceRevisionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfaceRevisionsWithResponse indicates an expected call of ListInterfaceRevisionsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfaceRevisionsWithResponse(ctx, interfaceId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfaceRevisionsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfaceRevisionsWithResponse), varargs...)
}

// ListInterfacesWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListInterfacesWithResponse(ctx context.Context, params *ListInterfacesParams, reqEditors ...RequestEditorFn) (*ListInterfacesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInterfacesWithResponse", varargs...)
	ret0, _ := ret[0].(*ListInterfacesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInterfacesWithResponse indicates an expected call of ListInterfacesWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListInterfacesWithResponse(ctx, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInterfacesWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListInterfacesWithResponse), varargs...)
}

// ListOrganizationMembersWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListOrganizationMembersWithResponse(ctx context.Context, organizationId OrganizationId, reqEditors ...RequestEditorFn) (*ListOrganizationMembersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOrganizationMembersWithResponse", varargs...)
	ret0, _ := ret[0].(*ListOrganizationMembersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationMembersWithResponse indicates an expected call of ListOrganizationMembersWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListOrganizationMembersWithResponse(ctx, organizationId any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationMembersWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListOrganizationMembersWithResponse), varargs...)
}

// ListOrganizationsWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) ListOrganizationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListOrganizationsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListOrganizationsWithResponse", varargs...)
	ret0, _ := ret[0].(*ListOrganizationsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizationsWithResponse indicates an expected call of ListOrganizationsWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) ListOrganizationsWithResponse(ctx any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizationsWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).ListOrganizationsWithResponse), varargs...)
}

// UpdateInterfaceWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateInterfaceWithBodyWithResponse(ctx context.Context, interfaceId InterfaceId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateInterfaceWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInterfaceWithBodyWithResponse indicates an expected call of UpdateInterfaceWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateInterfaceWithBodyWithResponse(ctx, interfaceId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterfaceWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateInterfaceWithBodyWithResponse), varargs...)
}

// UpdateInterfaceWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateInterfaceWithResponse(ctx context.Context, interfaceId InterfaceId, body UpdateInterfaceJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateInterfaceResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, interfaceId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateInterfaceWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateInterfaceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInterfaceWithResponse indicates an expected call of UpdateInterfaceWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateInterfaceWithResponse(ctx, interfaceId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, interfaceId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterfaceWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateInterfaceWithResponse), varargs...)
}

// UpdateOrganizationMemberWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationMemberWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationMemberWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMemberWithBodyWithResponse indicates an expected call of UpdateOrganizationMemberWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationMemberWithBodyWithResponse(ctx, organizationId, userId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMemberWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationMemberWithBodyWithResponse), varargs...)
}

// UpdateOrganizationMemberWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationMemberWithResponse(ctx context.Context, organizationId OrganizationId, userId UserId, body UpdateOrganizationMemberJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOrganizationMemberResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationMemberWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationMemberResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationMemberWithResponse indicates an expected call of UpdateOrganizationMemberWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationMemberWithResponse(ctx, organizationId, userId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, userId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationMemberWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationMemberWithResponse), varargs...)
}

// UpdateOrganizationWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationWithBodyWithResponse(ctx context.Context, organizationId OrganizationId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationWithBodyWithResponse indicates an expected call of UpdateOrganizationWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationWithBodyWithResponse(ctx, organizationId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationWithBodyWithResponse), varargs...)
}

// UpdateOrganizationWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateOrganizationWithResponse(ctx context.Context, organizationId OrganizationId, body UpdateOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateOrganizationResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, organizationId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateOrganizationWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateOrganizationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOrganizationWithResponse indicates an expected call of UpdateOrganizationWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateOrganizationWithResponse(ctx, organizationId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, organizationId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOrganizationWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateOrganizationWithResponse), varargs...)
}

// UpdateUserWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateUserWithBodyWithResponse(ctx context.Context, userId UserId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserWithBodyWithResponse indicates an expected call of UpdateUserWithBodyWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateUserWithBodyWithResponse(ctx, userId, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateUserWithBodyWithResponse), varargs...)
}

// UpdateUserWithResponse mocks base method.
func (m *MockClientWithResponsesIfc) UpdateUserWithResponse(ctx context.Context, userId UserId, body UpdateUserJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, userId, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUserWithResponse", varargs...)
	ret0, _ := ret[0].(*UpdateUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserWithResponse indicates an expected call of UpdateUserWithResponse.
func (mr *MockClientWithResponsesIfcMockRecorder) UpdateUserWithResponse(ctx, userId, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, userId, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserWithResponse", reflect.TypeOf((*MockClientWithResponsesIfc)(nil).UpdateUserWithResponse), varargs...)
}
